package com.example;
/*
 * 예외 처리 Exception handling 
 * 
 * 
 */
public class TryCatchExample {

	public static void main(String[] args) {
		
		int x = 3;
		
		try {
			int result = 10/0;		
		} catch (ArithmeticException e) {
			System.out.println(e.getMessage());
		}
		
		System.out.println("End.. ");
		
	}
	
	
	public static void main2(String[] args) {

		
		System.out.println("start");
		System.err.println("start");
		System.out.println("start");
		
		try {
			int result = 10/0;		// runtime exception을 조상으로 둔 예외클래스. 
		} catch (ArithmeticException e) {
			
		}
		
		
		
		
		System.out.println("End.. ");
		
	}

}
